version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"

    
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      pip-update:
        patterns:
          - "*"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "python"

  
